name: CI/CD Deploy to VPS (Docker)

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-app
  IMAGE_TAG: latest
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-app:latest

jobs:
  build-and-push:
    name: Build & Push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}
          platforms: linux/amd64
          build-args: |
            TG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }}
            TG_CHAT_ID=${{ secrets.TG_CHAT_ID }}
            NEXT_PUBLIC_BASE_URL=${{ secrets.BASE_URL }}
            NEXT_PUBLIC_TG_LINK=${{ secrets.TG_LINK }}
            NEXT_PUBLIC_GITHUB_LINK=${{ secrets.GH_LINK }}
            NEXT_PUBLIC_TG_GROUP_LINK=${{ secrets.TG_GROUP_LINK }}

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H "${{ secrets.REMOTE_HOST }}" >> ~/.ssh/known_hosts

      - name: Pull Docker image
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no \
            ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} \
            "docker pull ${{ env.IMAGE }}"

      - name: Stop old container
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no \
            ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} \
            "docker stop portfolio-app || true && docker rm portfolio-app || true"

      - name: Start new container
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no \
            ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} \
            "docker run -d --name portfolio-app --restart unless-stopped -p 3000:3000 --memory=900m --cpus='.5' ${{ env.IMAGE }}"
